version: 2.0
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 28eb57ab63aa0163f21d341acfc023bb4ea9e49b8db17ba440e99c9a16007700
    docker:
      - image: cimg/php:7.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            sudo -E install-php-extensions xdebug
            sudo composer self-update
            composer install -n --prefer-dist
            sudo docker-php-ext-enable xdebug
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            XDEBUG_MODE=coverage vendor/bin/phpunit --testsuite all --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
